### ISSUE TITLE
Build project (ng serve) is failing with angular 4.3.6 for "ngx-modialog": "^3.0.2"

### ISSUE THREAD

**Issue by yaswanthpsl** [shlomiassaf/ngx-modialog#399]
IMPORTANT: Please provide a sample using: http://plnkr.co/edit/lV7zsw7Yqossgs9JOfQU?p=preview

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use one of the templates above as a starting point).

package.json
    "@angular/animations": "^4.3.6",
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/router": "^4.3.6"

  "ngx-modialog": "^3.0.2"

`ERROR in /Users/blah/company-common-utils/src/app/utilsModule/utils.module.ts (17,32): Cannot find module 'ngx-modialog/plugins/vex'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ngx-modialog/plugins/vex relative to /Users/blah/company-common-utils/src/app/utilsModule/utils.module.ts., resolving symbol UtilsModule in /Users/blah/company-common-utils/src/app/utilsModule/utils.module.ts, resolving symbol UtilsModule in /Users/blah/company-common-utils/src/app/utilsModule/utils.module.ts
    at syntaxError (/Users/blah/company-common-utils/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/blah/company-common-utils/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/Users/blah/company-common-utils/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/Users/blah/company-common-utils/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/Users/blah/company-common-utils/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/blah/company-common-utils/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /Users/blah/company-common-utils/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/blah/company-common-utils/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/Users/blah/company-common-utils/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/blah/company-common-utils/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/blah/company-common-utils/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/blah/company-common-utils/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)`

* **What is the expected behavior?**
Everything was working correctly with angualr 4.3.5 version.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: ? 4.3.6
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Are there any breaking changes do I need to upgrade

**Comment by lubek1983** [comment]
the same problem here

**Comment by neoncube2** [comment]
I think I ran into this issue when using a version of TypeScript that was unsupported under the Angular version that I was using. In my case, the version of TypeScript was too high.
